@api = http://localhost:3000/tasks

###
GET http://localhost:3000/tasks

###
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "name": "create a website",
  "description": "using Nodejs and express"
}

### get total tasks
{{api}}/count